import type { AuditResult } from '@/lib/audit-schema';
import type { ClaimReport } from '@/lib/claim-report';

const aiSaasAudit: AuditResult = {
  audited_by: 'auditgpt.ai', verdict: 'C', verdict_header: 'Northwind AI — Workflow Automation SaaS', grade_stamp: 'C',
  company_info: 'Seed-stage AI workflow automation company. Founding year insufficient data.',
  report_card: ['Product page names specific integrations.', 'Pricing page is public with three tiers.'],
  support_gaps: ['Performance claims appear without a visible benchmark or source.', 'Customer-proof claims name no customers on the page.'],
  assumptions_to_test: [], website_fixes: [], recommended_next_steps: [], action_plan: [], industry_benchmarks_table: [],
  claim_audit: {
    summary: { total_claims: 3, verified_count: 0, weakly_supported_count: 1, unsupported_count: 1, overstated_count: 1, insufficient_public_evidence_count: 0, high_priority_count: 2, critical_priority_count: 0, claim_support_score: 42, executive_summary: 'Performance and customer-proof claims need clearer visible support. The strongest opportunity is to connect specific proof to the claims technical buyers are most likely to inspect.' },
    claims: [
      { id: 'claim-001', original_text: '10x faster than manual workflows', normalized_claim: 'Product is ten times faster than manual work.', source_url: 'https://example.com/product', source_type: 'product', claim_type: 'performance', claim_status: 'overstated', priority: 'high', visible_evidence: 'No benchmark, baseline, or methodology shown.', support_gap: 'Quantified speed claim with no stated baseline or source.', evidence_needed: 'A defined baseline and a repeatable benchmark methodology.', business_impact: 'Technical buyers need a clear basis for the comparison.', trust_gap: 'An unsourced number can read as marketing rather than measured performance.', positioning_risk: 'A speed multiple without context does not create a durable distinction.', safer_framing: 'Cut [task] from [X] minutes to [Y] in our [defined] benchmark.', proof_needed: ['Baseline definition', 'Benchmark methodology', 'Benchmark page'], recommended_next_step: 'add_proof' },
      { id: 'claim-002', original_text: 'Trusted by leading enterprises', normalized_claim: 'Major enterprises use the product.', source_url: 'https://example.com/', source_type: 'homepage', claim_type: 'customer_proof', claim_status: 'unsupported', priority: 'high', visible_evidence: 'No customer names, logos, or case studies on the page.', support_gap: 'Customer-proof claim with no named customer.', evidence_needed: 'Named logos or a case study with a consenting customer.', business_impact: 'Buyers need attributable proof during diligence.', trust_gap: 'The customer claim is difficult to verify from the page.', positioning_risk: 'Generic customer language is interchangeable with other vendors.', safer_framing: 'Used by [Customer A] and [Customer B] — see their results.', proof_needed: ['Customer quote', 'Consented case study', 'Source note'], recommended_next_step: 'add_proof' },
      { id: 'claim-003', original_text: 'Enterprise-ready security', normalized_claim: 'Product meets enterprise security expectations.', source_url: 'https://example.com/', source_type: 'homepage', claim_type: 'security', claim_status: 'weakly_supported', priority: 'medium', visible_evidence: 'The phrase is visible, but no supporting detail is linked.', support_gap: 'Security posture is asserted without an explanatory page.', evidence_needed: 'A page describing the practices and controls that are actually in place.', business_impact: 'Technical review needs accessible detail.', trust_gap: 'The claim leaves important buyer questions unanswered.', positioning_risk: 'The phrase alone is common across the category.', safer_framing: 'Our security practices include [practice] and [practice] — view the details.', proof_needed: ['Docs link', 'Security page', 'Stated controls'], recommended_next_step: 'add_proof' },
    ],
  },
  badge_eligibility: { eligible: false, badge_level: 'amber', badge_label: 'Review Recommended', public_verification_url: '' },
  disclaimer: '',
};

export const aiSaasClaimSupportFixture: ClaimReport = {
  fixtureLabel: 'Internal fixture — not live model output',
  metadata: { targetName: 'Northwind AI', targetUrl: 'https://example.com', reviewedSurface: 'Homepage, product, and security pages', auditDate: 'June 21, 2026', reportType: 'Claim Support Review', sealedHash: '58b4a970c8a24ef47f8b4c8cd1f349f2e30eef3146cfaf5b23cf26c34ca146f8', sealedAt: '2026-06-21T14:32:00-04:00' },
  executiveVerdict: 'Northwind AI communicates a clear product direction, but its strongest performance and customer-proof claims need more visible support. The immediate proof opportunity is to add a defined benchmark, attributable customer evidence, and accessible security detail before relying on broader positioning language.',
  audit: aiSaasAudit,
};

export const medSpaFoundersAuditFixture: ClaimReport = {
  fixtureLabel: 'Internal fixture — fictional composite — not live model output',
  metadata: { targetName: 'Aurelia Aesthetics', targetUrl: 'https://example.com', reviewedSurface: 'Homepage and service pages', auditDate: 'June 21, 2026', reportType: 'Founder’s Audit' },
  executiveVerdict: 'Aurelia presents a polished premium brand, while several prominent claims need more visible support. The clearest proof opportunities are practitioner context, consented result examples, and an attributable review count paired with safer framing.',
  audit: { ...aiSaasAudit, verdict_header: 'Aurelia Aesthetics — Premium Med-Spa', company_info: 'Fictional composite used only as internal test data.', claim_audit: { summary: { ...aiSaasAudit.claim_audit.summary, executive_summary: 'Premium positioning needs more visible, attributable support.' }, claims: [
    { ...aiSaasAudit.claim_audit.claims[0], id: 'med-001', original_text: "NYC’s premier med-spa", normalized_claim: 'Clinic is positioned as a leading med-spa in NYC.', source_url: 'https://example.com/', source_type: 'homepage', claim_type: 'market_leadership', claim_status: 'overstated', priority: 'medium', visible_evidence: 'None on page.', support_gap: 'No visible basis for the superlative.', evidence_needed: 'A specific, verifiable distinction.', business_impact: 'Specific distinctions are more useful to prospective customers than broad adjectives.', trust_gap: 'The reader cannot connect the positioning to visible proof.', positioning_risk: 'The phrase sounds similar to common category positioning.', safer_framing: 'Practitioner-led aesthetic care in [neighborhood].', proof_needed: ['Methodology note', 'Verifiable distinction'] },
    { ...aiSaasAudit.claim_audit.claims[1], id: 'med-002', original_text: 'Natural-looking results', normalized_claim: 'Services are positioned around natural-looking outcomes.', source_url: 'https://example.com/services', source_type: 'product', claim_type: 'performance', visible_evidence: 'No result examples are visible on the reviewed page.', support_gap: 'Outcome framing appears without visible examples.', evidence_needed: 'Consented examples with clear context and timeframe.', business_impact: 'Prospective customers need examples to understand the intended aesthetic.', trust_gap: 'The outcome description cannot be evaluated from the page.', positioning_risk: 'The phrase is widely used and needs specific proof to stand apart.', safer_framing: 'Explore consented examples with [service], [timeframe], and individual context.', proof_needed: ['Consented examples', 'Timeframe', 'Methodology note'] },
    { ...aiSaasAudit.claim_audit.claims[2], id: 'med-003', original_text: 'Trusted by thousands of customers', normalized_claim: 'Thousands of customers have used the business.', claim_type: 'customer_proof', source_type: 'homepage', claim_status: 'weakly_supported', priority: 'high', visible_evidence: 'No review count or attributable quotes are shown on the page.', support_gap: 'The stated number has no visible source.', evidence_needed: 'A current, attributable review count and source link.', business_impact: 'Attributable social proof makes the statement easier to evaluate.', trust_gap: 'The count cannot be confirmed from the reviewed surface.', positioning_risk: 'A broad volume claim adds little distinction without context.', safer_framing: '[X] customer reviews as of [date] — view the source.', proof_needed: ['Source link', 'Timeframe', 'Customer quote'] },
  ] } },
};
