export type CityData = {
  slug: string;
  name: string;
  state: string;
};

export const topCities: CityData[] = [
  { slug: 'new-york', name: 'New York', state: 'NY' },
  { slug: 'los-angeles', name: 'Los Angeles', state: 'CA' },
  { slug: 'chicago', name: 'Chicago', state: 'IL' },
  { slug: 'houston', name: 'Houston', state: 'TX' },
  { slug: 'phoenix', name: 'Phoenix', state: 'AZ' },
  { slug: 'philadelphia', name: 'Philadelphia', state: 'PA' },
  { slug: 'san-antonio', name: 'San Antonio', state: 'TX' },
  { slug: 'san-diego', name: 'San Diego', state: 'CA' },
  { slug: 'dallas', name: 'Dallas', state: 'TX' },
  { slug: 'san-jose', name: 'San Jose', state: 'CA' },
  { slug: 'austin', name: 'Austin', state: 'TX' },
  { slug: 'jacksonville', name: 'Jacksonville', state: 'FL' },
  { slug: 'fort-worth', name: 'Fort Worth', state: 'TX' },
  { slug: 'columbus', name: 'Columbus', state: 'OH' },
  { slug: 'indianapolis', name: 'Indianapolis', state: 'IN' },
  { slug: 'charlotte', name: 'Charlotte', state: 'NC' },
  { slug: 'san-francisco', name: 'San Francisco', state: 'CA' },
  { slug: 'seattle', name: 'Seattle', state: 'WA' },
  { slug: 'denver', name: 'Denver', state: 'CO' },
  { slug: 'washington', name: 'Washington', state: 'DC' },
  { slug: 'nashville', name: 'Nashville', state: 'TN' },
  { slug: 'oklahoma-city', name: 'Oklahoma City', state: 'OK' },
  { slug: 'el-paso', name: 'El Paso', state: 'TX' },
  { slug: 'boston', name: 'Boston', state: 'MA' },
  { slug: 'portland', name: 'Portland', state: 'OR' },
  { slug: 'las-vegas', name: 'Las Vegas', state: 'NV' },
  { slug: 'detroit', name: 'Detroit', state: 'MI' },
  { slug: 'memphis', name: 'Memphis', state: 'TN' },
  { slug: 'louisville', name: 'Louisville', state: 'KY' },
  { slug: 'baltimore', name: 'Baltimore', state: 'MD' },
  { slug: 'milwaukee', name: 'Milwaukee', state: 'WI' },
  { slug: 'albuquerque', name: 'Albuquerque', state: 'NM' },
  { slug: 'tucson', name: 'Tucson', state: 'AZ' },
  { slug: 'fresno', name: 'Fresno', state: 'CA' },
  { slug: 'sacramento', name: 'Sacramento', state: 'CA' },
  { slug: 'mesa', name: 'Mesa', state: 'AZ' },
  { slug: 'kansas-city', name: 'Kansas City', state: 'MO' },
  { slug: 'atlanta', name: 'Atlanta', state: 'GA' },
  { slug: 'omaha', name: 'Omaha', state: 'NE' },
  { slug: 'colorado-springs', name: 'Colorado Springs', state: 'CO' },
  { slug: 'raleigh', name: 'Raleigh', state: 'NC' },
  { slug: 'miami', name: 'Miami', state: 'FL' },
  { slug: 'virginia-beach', name: 'Virginia Beach', state: 'VA' },
  { slug: 'oakland', name: 'Oakland', state: 'CA' },
  { slug: 'minneapolis', name: 'Minneapolis', state: 'MN' },
  { slug: 'tulsa', name: 'Tulsa', state: 'OK' },
  { slug: 'arlington', name: 'Arlington', state: 'TX' },
  { slug: 'new-orleans', name: 'New Orleans', state: 'LA' },
  { slug: 'wichita', name: 'Wichita', state: 'KS' },
  { slug: 'cleveland', name: 'Cleveland', state: 'OH' },
];
