import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUserId, getActiveSubscription } from '@/lib/subscription';
import { db } from '@/lib/db';
import { createFixPR, generateFixFiles } from '@/lib/github-deploy';

export const runtime = 'nodejs';
export const maxDuration = 60;

export async function POST(request: NextRequest) {
  try {
    // ── Auth ──────────────────────────────────────────────────
    const userId = await getCurrentUserId();
    if (!userId) {
      return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
    }

    // ── Subscription check ────────────────────────────────────
    const sub = await getActiveSubscription();
    if (!sub) {
      return NextResponse.json(
        { error: 'Pro subscription required', code: 'SUBSCRIPTION_REQUIRED' },
        { status: 402 },
      );
    }

    // ── Input ─────────────────────────────────────────────────
    const { publicId } = await request.json();
    if (!publicId || typeof publicId !== 'string') {
      return NextResponse.json({ error: 'publicId is required' }, { status: 400 });
    }

    // ── Load audit ────────────────────────────────────────────
    const audit = await db.audit.findUnique({
      where: { publicId },
      select: {
        id: true,
        publicId: true,
        companyName: true,
        userId: true,
        auditJson: true,
      },
    });

    if (!audit) {
      return NextResponse.json({ error: 'Audit not found' }, { status: 404 });
    }
    if (audit.userId !== userId) {
      return NextResponse.json({ error: 'Not your audit' }, { status: 403 });
    }

    // ── Parse audit JSON ──────────────────────────────────────
    let auditJson: any;
    try {
      auditJson = JSON.parse(audit.auditJson);
    } catch {
      return NextResponse.json({ error: 'Invalid audit data' }, { status: 500 });
    }

    // ── Generate fix files ────────────────────────────────────
    const files = generateFixFiles(auditJson);
    if (files.length === 0) {
      return NextResponse.json(
        { error: 'No fixable content found in this audit' },
        { status: 400 },
      );
    }

    // ── Create or update PR ───────────────────────────────────
    const appUrl = process.env.NEXT_PUBLIC_URL || 'http://localhost:3000';
    const evidenceUrl = `${appUrl}/audit/${audit.publicId}`;

    const fixes = Array.isArray(auditJson.website_fixes)
      ? auditJson.website_fixes.map((f: string, i: number) => `${i + 1}. ${f}`).join('\n')
      : 'No specific fixes listed.';

    const prBody = [
      `## AuditGPT Fixes`,
      `**Score:** ${auditJson.score ?? 'N/A'}/100`,
      `**Grade:** ${auditJson.verdict ?? auditJson.grade_stamp ?? 'N/A'}`,
      '',
      '### Changes in this PR',
      fixes,
      '',
      '### Evidence',
      `[View full audit report](${evidenceUrl})`,
      '',
      '---',
      `*Generated by AuditGPT — The Truth Engine for AI Businesses.*`,
    ].join('\n');

    const result = await createFixPR({
      userId,
      auditPublicId: audit.publicId,
      auditId: audit.id,
      companyName: audit.companyName,
      files,
      commitMessage: `fix: apply AuditGPT recommendations (${audit.publicId})`,
      prTitle: `AuditGPT Fixes for ${audit.companyName || 'website'}`,
      prBody,
    });

    return NextResponse.json(result);
  } catch (error: any) {
    console.error('Deploy fix error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create PR' },
      { status: 500 },
    );
  }
}
